# Default values for webapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

hpa:
  enabled: true
  replicaCount: 1
  minReplicas: 1
  maxReplicas: 4
  cpu: 20

image:
  repository: ysukhy/myimage
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: webapp.avik.zp.ua
      paths:
        path: /

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
   requests:
     cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
